from dataclasses import replace
from importlib.metadata import version
from pathlib import Path

from click.testing import CliRunner

from omniship.cli import update as update_module
from omniship.cli.app import cli
from omniship.plugins.github.dependencies import GitHubActionLock


def test_update_refreshes_one_github_action(
    tmp_path: Path,
    monkeypatch,
) -> None:
    lock_path = tmp_path / "omniship.lock"
    original = GitHubActionLock.defaults()
    lock_path.write_text(original.render(), encoding="utf-8")
    updated_sha = "a" * 40

    def resolve(pin):
        assert pin.name == "deploy-pages"
        return replace(pin, version="v5.1.0", sha=updated_sha)

    monkeypatch.setattr(update_module, "resolve_action", resolve)

    result = CliRunner().invoke(
        cli,
        [
            "update",
            "github/actions/deploy-pages",
            "--lock-file",
            str(lock_path),
        ],
    )

    assert result.exit_code == 0, result.output
    updated = GitHubActionLock.load(lock_path)
    assert updated.get("deploy-pages").version == "v5.1.0"
    assert updated.get("deploy-pages").sha == updated_sha
    assert updated.get("checkout") == original.get("checkout")
    assert "Run 'omniship generate'" in result.output


def test_update_rejects_an_unknown_dependency(tmp_path: Path) -> None:
    result = CliRunner().invoke(
        cli,
        [
            "update",
            "github/actions/unknown",
            "--lock-file",
            str(tmp_path / "omniship.lock"),
        ],
    )

    assert result.exit_code == 1
    assert "Unknown GitHub Action dependency" in result.output


def test_update_refreshes_the_locked_omniship_version(tmp_path: Path) -> None:
    lock_path = tmp_path / "omniship.lock"
    original = GitHubActionLock.defaults().with_omniship_version("0.0.9")
    lock_path.write_text(original.render(), encoding="utf-8")

    result = CliRunner().invoke(
        cli,
        [
            "update",
            "omniship",
            "--lock-file",
            str(lock_path),
        ],
    )

    assert result.exit_code == 0, result.output
    updated = GitHubActionLock.load(lock_path)
    assert updated.omniship_version == version("omniship")
    assert updated.actions == original.actions
    assert f"Updated omniship to {version('omniship')}" in result.output


def test_update_restores_missing_actions_from_plugin_defaults(
    tmp_path: Path,
    monkeypatch,
) -> None:
    lock_path = tmp_path / "omniship.lock"
    lock_path.write_text(
        "# Generated by OmniShip\nversion = 1\n",
        encoding="utf-8",
    )
    resolved: list[str] = []

    def resolve(pin):
        resolved.append(pin.name)
        return pin

    monkeypatch.setattr(update_module, "resolve_action", resolve)

    result = CliRunner().invoke(
        cli,
        ["update", "--lock-file", str(lock_path)],
    )

    assert result.exit_code == 0, result.output
    updated = GitHubActionLock.load(lock_path)
    assert updated.get("checkout").repository == "actions/checkout"
    assert set(resolved) == set(GitHubActionLock.defaults().actions)
