from __future__ import annotations

import json
import os
import re
import subprocess
import tomllib
import urllib.request
from dataclasses import dataclass, replace
from importlib import resources
from importlib.metadata import version as distribution_version
from pathlib import Path
from typing import Any
from urllib.parse import quote

from omniship.core.execution import SecretRef
from omniship.workflow.model import GitPluginPackage, PluginIndex, PluginPackage

LOCK_VERSION = 1
LOCK_FILENAME = "omniship.lock"
LOCK_MARKER = "# Generated by OmniShip. Update with `omniship update`."
_SEMVER_PATTERN = re.compile(r"^v?(\d+)\.(\d+)\.(\d+)$")
_SHA_PATTERN = re.compile(r"^[0-9a-f]{40}$")
_NAME_PATTERN = re.compile(r"^[a-z0-9-]+$")
_REPOSITORY_PATTERN = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")


@dataclass(frozen=True, slots=True)
class GitHubActionPin:
    name: str
    repository: str
    major: int
    version: str
    sha: str

    def __post_init__(self) -> None:
        if not _NAME_PATTERN.fullmatch(self.name):
            raise ValueError(f"Invalid GitHub Action dependency name: {self.name}")
        if not _REPOSITORY_PATTERN.fullmatch(self.repository):
            raise ValueError(f"Invalid GitHub Action repository: {self.repository}")
        if not isinstance(self.major, int) or self.major < 1:
            raise ValueError("GitHub Action major version must be a positive integer")
        version = _SEMVER_PATTERN.fullmatch(self.version)
        if version is None or int(version.group(1)) != self.major:
            raise ValueError(
                f"GitHub Action version '{self.version}' does not match major {self.major}"
            )
        if _SHA_PATTERN.fullmatch(self.sha) is None:
            raise ValueError(
                "GitHub Action pin must use a full 40-character commit SHA"
            )

    @property
    def reference(self) -> str:
        return f"{self.repository}@{self.sha}"


@dataclass(frozen=True)
class GitHubActionLock:
    actions: dict[str, GitHubActionPin]
    omniship_version: str
    plugins: tuple[PluginPackage | GitPluginPackage, ...] = ()

    def __post_init__(self) -> None:
        if not isinstance(self.omniship_version, str) or not self.omniship_version:
            raise ValueError("Locked OmniShip version must be a non-empty string")

    @classmethod
    def defaults(cls) -> GitHubActionLock:
        content = (
            resources.files("omniship.plugins.github")
            .joinpath("actions.defaults.toml")
            .read_text(encoding="utf-8")
        )
        return cls._parse(content, source="bundled GitHub Action defaults")

    @classmethod
    def load(cls, path: str | Path) -> GitHubActionLock:
        lock_path = Path(path)
        return cls._parse(
            lock_path.read_text(encoding="utf-8"),
            source=str(lock_path),
        )

    @classmethod
    def _parse(cls, content: str, *, source: str) -> GitHubActionLock:
        try:
            document = tomllib.loads(content)
            if document.get("version") != LOCK_VERSION:
                raise ValueError(f"Unsupported OmniShip lock version in {source}")
            entries = document.get("github", {}).get("actions", {})
            if not isinstance(entries, dict):
                raise ValueError(f"Invalid GitHub Actions lock data in {source}")
            omniship = document.get("omniship", {})
            if not isinstance(omniship, dict):
                raise ValueError(f"Invalid OmniShip dependency data in {source}")
            omniship_version = omniship.get(
                "version",
                distribution_version("omniship"),
            )
            actions = {
                name: GitHubActionPin(name=name, **values)
                for name, values in entries.items()
            }
            plugin_entries = document.get("plugins", {})
            if not isinstance(plugin_entries, dict):
                raise ValueError(f"Invalid plugin dependency data in {source}")
            plugins = tuple(
                PluginPackage(name, version) for name, version in plugin_entries.items()
            )
            source_entries = document.get("plugin_sources", [])
            if not isinstance(source_entries, list):
                raise ValueError(f"Invalid plugin source data in {source}")
            source_plugins: list[PluginPackage | GitPluginPackage] = []
            for entry in source_entries:
                if not isinstance(entry, dict):
                    raise ValueError(f"Invalid plugin source data in {source}")
                if entry.get("type") == "index":
                    source_plugins.append(
                        PluginPackage(
                            entry["name"],
                            entry["version"],
                            index=PluginIndex(
                                entry["index_name"],
                                entry["url"],
                                password=SecretRef(entry["password_secret"]),
                                username=entry["username"],
                            ),
                        )
                    )
                elif entry.get("type") == "git":
                    source_plugins.append(
                        GitPluginPackage(
                            entry["name"],
                            entry["repository"],
                            entry["commit"],
                            version=entry.get("version"),
                        )
                    )
                else:
                    raise ValueError(f"Unknown plugin source type in {source}")
            plugins += tuple(source_plugins)
        except (KeyError, TypeError, tomllib.TOMLDecodeError) as exc:
            raise ValueError(f"Invalid OmniShip lock file {source}: {exc}") from exc
        return cls(actions, omniship_version, plugins)

    def get(self, name: str) -> GitHubActionPin:
        try:
            return self.actions[name]
        except KeyError as exc:
            raise ValueError(
                f"GitHub Action dependency '{name}' is missing from omniship.lock; "
                "run 'omniship update'"
            ) from exc

    def reference(self, name: str) -> str:
        return self.get(name).reference

    def select(self, selector: str | None = None) -> tuple[GitHubActionPin, ...]:
        if selector is None:
            return tuple(self.actions.values())
        for action in self.actions.values():
            if selector in {
                action.name,
                action.repository,
                f"github/{action.repository}",
            }:
                return (action,)
        raise ValueError(f"Unknown GitHub Action dependency: {selector}")

    def with_pin(self, pin: GitHubActionPin) -> GitHubActionLock:
        actions = dict(self.actions)
        actions[pin.name] = pin
        return GitHubActionLock(actions, self.omniship_version, self.plugins)

    def with_omniship_version(self, version: str) -> GitHubActionLock:
        return GitHubActionLock(dict(self.actions), version, self.plugins)

    def with_plugins(
        self, plugins: tuple[PluginPackage | GitPluginPackage, ...]
    ) -> GitHubActionLock:
        return GitHubActionLock(dict(self.actions), self.omniship_version, plugins)

    def validate_compatibility(self, defaults: GitHubActionLock) -> None:
        for name, expected in defaults.actions.items():
            actual = self.get(name)
            if (
                actual.repository != expected.repository
                or actual.major != expected.major
            ):
                raise ValueError(
                    f"GitHub Action dependency '{name}' is incompatible with "
                    "the installed GitHub plugin; run 'omniship update'"
                )

    def render(self) -> str:
        lines = [
            LOCK_MARKER,
            f"version = {LOCK_VERSION}",
            "",
            "[omniship]",
            f"version = {json.dumps(self.omniship_version)}",
        ]
        if self.plugins:
            published = [
                plugin
                for plugin in self.plugins
                if isinstance(plugin, PluginPackage) and plugin.index is None
            ]
            if published:
                lines.extend(["", "[plugins]"])
            for plugin in published:
                lines.append(
                    f"{json.dumps(plugin.name)} = {json.dumps(plugin.version)}"
                )
            for plugin in self.plugins:
                if isinstance(plugin, GitPluginPackage):
                    if plugin.commit is None:
                        raise ValueError(
                            f"Git plugin '{plugin.name}' has no locked commit"
                        )
                    lines.extend(
                        [
                            "",
                            "[[plugin_sources]]",
                            'type = "git"',
                            f"name = {json.dumps(plugin.name)}",
                            f"repository = {json.dumps(plugin.repository)}",
                            f"commit = {json.dumps(plugin.commit)}",
                        ]
                    )
                    if plugin.version is not None:
                        lines.append(f"version = {json.dumps(plugin.version)}")
                elif plugin.index is not None:
                    index = plugin.index
                    lines.extend(
                        [
                            "",
                            "[[plugin_sources]]",
                            'type = "index"',
                            f"name = {json.dumps(plugin.name)}",
                            f"version = {json.dumps(plugin.version)}",
                            f"index_name = {json.dumps(index.name)}",
                            f"url = {json.dumps(index.url)}",
                            f"username = {json.dumps(index.username)}",
                            f"password_secret = {json.dumps(index.password.name)}",
                        ]
                    )
        for action in self.actions.values():
            lines.extend(
                [
                    "",
                    f"[github.actions.{action.name}]",
                    f"repository = {json.dumps(action.repository)}",
                    f"major = {action.major}",
                    f"version = {json.dumps(action.version)}",
                    f"sha = {json.dumps(action.sha)}",
                ]
            )
        return "\n".join(lines) + "\n"


def resolve_git_plugin(plugin: GitPluginPackage) -> GitPluginPackage:
    """Resolve an exact Git version tag, preferring an annotated tag's commit."""
    if plugin.version is None:
        return plugin
    ref = f"refs/tags/{plugin.version}"
    command = [
        "git",
        "ls-remote",
        "--exit-code",
        "--tags",
        plugin.repository,
        ref,
        f"{ref}^{{}}",
    ]
    try:
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=30,
            env={**os.environ, "GIT_TERMINAL_PROMPT": "0"},
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise ValueError(
            f"Could not resolve Git plugin tag '{plugin.version}' for {plugin.name}"
        ) from exc
    if result.returncode != 0:
        raise ValueError(
            f"Could not resolve Git plugin tag '{plugin.version}' for {plugin.name} "
            f"(git exit code {result.returncode})"
        )
    refs = {}
    for line in result.stdout.splitlines():
        parts = line.split("\t", 1)
        if len(parts) == 2 and re.fullmatch(r"[0-9a-fA-F]{40}", parts[0]):
            refs[parts[1]] = parts[0]
    commit = refs.get(f"{ref}^{{}}") or refs.get(ref)
    if commit is None:
        raise ValueError(
            f"Git plugin tag '{plugin.version}' for {plugin.name} did not resolve to a commit"
        )
    return replace(plugin, commit=commit)


def resolve_action(pin: GitHubActionPin) -> GitHubActionPin:
    releases = _github_json(f"/repos/{pin.repository}/releases?per_page=100")
    candidates: list[tuple[tuple[int, int, int], str]] = []
    for release in releases:
        if release.get("draft") or release.get("prerelease"):
            continue
        tag = release.get("tag_name")
        version = _SEMVER_PATTERN.fullmatch(tag) if isinstance(tag, str) else None
        if version is None or int(version.group(1)) != pin.major:
            continue
        candidates.append((tuple(int(part) for part in version.groups()), tag))
    if not candidates:
        raise ValueError(f"No stable v{pin.major} release found for {pin.repository}")
    _, version = max(candidates)
    commit = _github_json(f"/repos/{pin.repository}/commits/{quote(version, safe='')}")
    sha = commit.get("sha")
    if not isinstance(sha, str):
        raise ValueError(f"GitHub did not return a commit SHA for {pin.repository}")
    return replace(pin, version=version, sha=sha)


def _github_json(path: str) -> Any:
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "OmniShip",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if token := os.environ.get("GITHUB_TOKEN"):
        headers["Authorization"] = f"Bearer {token}"
    request = urllib.request.Request(
        f"https://api.github.com{path}",
        headers=headers,
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            return json.loads(response.read().decode("utf-8"))
    except Exception as exc:
        raise ValueError(f"Could not resolve GitHub Action dependency: {exc}") from exc
