from dataclasses import replace
from importlib.metadata import version
from pathlib import Path

import pytest

from omniship.plugins.github import dependencies
from omniship.plugins.github.dependencies import (
    GitHubActionLock,
    GitHubActionPin,
    resolve_action,
)


def test_default_action_lock_is_complete_and_round_trips(tmp_path: Path) -> None:
    lock = GitHubActionLock.defaults()
    path = tmp_path / "omniship.lock"

    path.write_text(lock.render(), encoding="utf-8")
    restored = GitHubActionLock.load(path)

    assert restored == lock
    assert restored.reference("checkout").startswith("actions/checkout@")
    assert restored.omniship_version == version("omniship")
    assert f'[omniship]\nversion = "{version("omniship")}"' in lock.render()
    assert len(restored.get("checkout").sha) == 40
    assert restored.get("checkout").major == 7
    assert lock.render().startswith("# Generated by OmniShip")


def test_action_lock_rejects_missing_required_action(tmp_path: Path) -> None:
    path = tmp_path / "omniship.lock"
    path.write_text("version = 1\n", encoding="utf-8")

    lock = GitHubActionLock.load(path)

    with pytest.raises(ValueError, match="checkout.*omniship update"):
        lock.reference("checkout")


def test_action_lock_selects_full_github_dependency_name() -> None:
    lock = GitHubActionLock.defaults()

    selected = lock.select("github/actions/deploy-pages")

    assert selected == (lock.get("deploy-pages"),)


def test_action_pin_requires_a_full_commit_sha() -> None:
    with pytest.raises(ValueError, match="full 40-character commit SHA"):
        GitHubActionPin(
            name="checkout",
            repository="actions/checkout",
            major=7,
            version="v7.0.1",
            sha="abc123",
        )


def test_action_resolver_selects_latest_stable_compatible_release(
    monkeypatch,
) -> None:
    pin = GitHubActionLock.defaults().get("deploy-pages")
    updated_sha = "b" * 40
    requests: list[str] = []

    def github_json(path: str):
        requests.append(path)
        if "/releases?" in path:
            return [
                {"tag_name": "v6.0.0", "draft": False, "prerelease": False},
                {"tag_name": "v5.2.0", "draft": False, "prerelease": True},
                {"tag_name": "v5.1.0", "draft": False, "prerelease": False},
                {"tag_name": "v5.0.2", "draft": False, "prerelease": False},
            ]
        return {"sha": updated_sha}

    monkeypatch.setattr(dependencies, "_github_json", github_json)

    updated = resolve_action(pin)

    assert updated.version == "v5.1.0"
    assert updated.sha == updated_sha
    assert requests[-1] == "/repos/actions/deploy-pages/commits/v5.1.0"


def test_action_lock_rejects_a_pin_outside_plugin_compatibility() -> None:
    defaults = GitHubActionLock.defaults()
    incompatible = defaults.with_pin(
        replace(
            defaults.get("checkout"),
            major=6,
            version="v6.0.0",
        )
    )

    with pytest.raises(ValueError, match="checkout.*incompatible.*omniship update"):
        incompatible.validate_compatibility(defaults)
